FROM oven/bun:latest AS builder

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install

COPY . .

RUN bun run build

FROM busybox AS frontend-dist
COPY --from=builder /app/dist /app/dist

CMD echo "Built frontend."
